### ISSUE TITLE
Spelling issue ?

### ISSUE THREAD

**Issue by abdurrahmanarikan** [Kelindar/iss#1]
I might be wrong, or misunderstood, is there any spelling issue on your readme file ?

which "polls" (pulls maybe ?) the location and the browser which renders it.

**Comment by kelindar** [comment]
It refers to polling (see [wiki/polling](https://en.wikipedia.org/wiki/Polling_(computer_science))). It's basically periodically checks the location by reading it, as opposed to "push" where the data in pushed directly to the client by a remote server.

**Comment by abdurrahmanarikan** [comment]
Ok, Thanks for the complementary comment though.
